# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 幻圣的空间
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ch"
url: "http://cheungwoonming.github.io" # the base hostname & protocol for your site
twitter_username: 幻圣
github_username: CheungWoonMing
disqus_username:

# Pagination
paginate: 2

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

gitalk:
  clientID: ac91e3a3714342401e59
  clientSecret: 1fbd8f4cc27a26ed5098b23e299ea8d26b0999fb
  repo: cheungwoonming.github.io
  owner: cheungwoonming

footer-links:
  email: huanmingzhang@qq.com
  github: cheungwoonming
  zhihu: huan-sheng-19-28
  bilibili: 85885497
  # https://space.bilibili.com/85885497
  #weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
